import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";

const geistSans = Lexend({
    variable: "--font-lexend",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body className={`${geistSans.variable} antialiased`}>{children}</body>
        </html>
    );
}
